
linters: 
  disable-all: true
  enable:
    - gosimple
    - errcheck
    - staticcheck
    - asciicheck
    - bodyclose
    - goconst
    - unused
    - ineffassign
    - govet
    - gofmt
    - godot
    - goimports
    - misspell
    - godox
    - nestif

linters-settings:
  errcheck:
    ignore: ''
  nestif:
    min-complexity: 4
