version: 2

builds:
  - goos:
    - linux
    - darwin

release:
  header: |
    # Changelog ({{ .Date }})
    All notable changes to this project will be documented in this file.
  footer: |
    Thanks for using this project!