name: Golang Linter & Tests
description: Run Golang Linter and Tests

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: latest

    - name: Verify Dependencies
      working-directory: ./
      run: go mod verify

    - name: Go Linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: 'latest'

    - name: Build
      working-directory: ./
      run: go build -v ./...

    - name: Test
      working-directory: ./
      run: go test -vet=off ./...