name: CI Go Tests

on:
  push:
    branches:
      - 'main'

jobs: 
  tests: 
    name: Run Tests
    strategy:
      matrix:
        go-version: [1.21]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps: 
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Verify Dependencies
        working-directory: ./
        run: go mod verify
      - name: build
        working-directory: ./
        run: go build -v ./...
      - name: Test
        working-directory: ./
        run: go test -vet=off ./...