name: Automatic Release based on Tag

on:
  push:
    tags:
      - 'v*'
      
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linter & Tests
        uses: ./.github/actions/linter

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}